import numpy as np
import sys
import pathlib

top_dir = str(pathlib.Path(__file__).parents[2])
sys.path.append(top_dir)
from pyrecon.mlem._projector import get_forward_projection, get_backward_projection

subset_idx = int(sys.argv[1])
sysmat_path = f""        #replace with system matrix path generated by previous code 
proj_path = f""           #Same as above for projections

sysmat = np.load(sysmat_path)["sysmat"]            # Shape: (projections, voxels)
projection = np.load(proj_path)["projection"]      # Shape: (projections,)

n_voxels = sysmat.shape[1]
image_est = np.ones(n_voxels)

n_iter = 2
for _ in range(n_iter):
    forward = get_forward_projection(sysmat, image_est)
    ratio = projection / np.clip(forward, 1e-6, None)
    back = get_backward_projection(sysmat, image_est, ratio)  # ✅ Fixed here
    norm = np.sum(sysmat, axis=0)
    image_est *= back / np.clip(norm, 1e-6, None)

np.savez_compressed(f"", image=image_est) #replace with your output folder
